### ISSUE TITLE
Setup Codepaces or Gitpod with the prototype kit

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/nhsuk-prototype-kit#162]
## Description

Setup [Codespaces](https://github.com/features/codespaces) or [Gitpod](https://www.gitpod.io
) to allow for the prototype kit to be ran in IDE (Integrated Development Environment) in the browser. This will help reduce the barrier to entry and resolve any permission issues when installing Node.js on devices (which we often see on NHSD corporate devices). 

Codespaces would be the preference if we can get access to the early BETA before its official launch. Setup the GitHub integration with the prototype kit and add any documentation for running the project within Codespaces.

**Comment by DomBaker** [comment]
Due to Codespaces still being in a beta stage and incurs cost implications - Gitpod is more established and documented with a high level of support if required.

- [x] Add GitPods yml file - docs found [here](https://www.gitpod.io/docs)
- [x] Add GitPods button to contribution section of README
- [x] Add GitPods application to NHSUK Org in Github - scoped to nhsuk-prototype-kit
- [x] Create Pre-build for prototype Gitpods
