### ISSUE TITLE
How to guide: Passing data page to page example - Incorrect page links

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/nhsuk-prototype-kit#65]
On the How to pass data page to page example (https://nhsuk-prototype-kit.azurewebsites.net/examples/passing-data/register-gp-step1) both the **Yes** and **No** radio button options lead to the same page of https://nhsuk-prototype-kit.azurewebsites.net/examples/passing-data/register-gp-step2

I would expect them to lead to different pages depending on your answer - it also isn't obvious where it is passing data or what the example of passing data is until 5 steps into the process. Maybe cut down the passing data functionality to just 1 form page?

**Comment by mcheung-nhs** [comment]
@AdamChrimes - The idea is to show the different types of inputs that can be used to pass data, i.e. radio buttons, text fields and checkboxes. We can remove any confusion with the yes or no button options leading to the same page by removing the "Enter your NHS number" page as this a text field which is replicated in the "What is your name" page. I think we should keep the multiple pages rather than have it all on one page, so as to adhere to the recommended pattern of 1 question per page and reflect a real life journey.

What do you think @davidhunter08?

**Comment by chrimesdev** [comment]
This was fixed in release 1.0.3
